Error message for _extr_sums changed.
New GNU GCC astyle wrapper added.

diff --git a/boilerplate/_extr_sums b/boilerplate/_extr_sums
--- a/boilerplate/_extr_sums
+++ b/boilerplate/_extr_sums
@@ -4,7 +4,7 @@
 # specified by the first parameter.
 
 if [ -z "$1" ] ; then
-    echo "Param missing. Usage __extr_testlogs destdir" >&2
+    echo "Param missing. Usage _extr_sums destdir" >&2
     exit 1
 fi
 
